name: Keep Streamlit Awake

on:
  schedule:
    - cron: '*/25 * * * *'
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install playwright
          npx playwright install chromium
          node -e "
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch();
            const page = await browser.newPage();
            await page.goto('https://apiusage-4danalyzer-main-z9fynz.streamlit.app/', { waitUntil: 'domcontentloaded' });
            await page.goto('https://cryptoanalyzer-j92kytncetjxksx5siflxf.streamlit.app/', { waitUntil: 'domcontentloaded' });
            await browser.close();
          })();"
