name: Scrape 4D

on:
  schedule:
    - cron: '0 11 * * 3,6,0'   # 7:00 PM SGT
    - cron: '10 11 * * 3,6,0'  # 7:10 PM SGT
    - cron: '0 12 * * 3,6,0'   # 8:00 PM SGT
    - cron: '1 12 * * 3,6,0'   # 8:01 PM SGT
  workflow_dispatch:

jobs:
  scrape:
    if: github.event.schedule != '1 12 * * 3,6,0' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }
      - run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm run scrape
      - name: Commit scrape results
        env: { PAT: ${{ secrets.PAT }} }
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add 4d.json
          git commit -m "Update 4D results" || echo "No changes"
          git pull --rebase origin main || true
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} HEAD:main

  process:
    if: github.event.schedule == '1 12 * * 3,6,0' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          pip install --no-cache-dir openpyxl pandas requests
          python 4djson_Append_to_Excel.py
          python 4dbox_script.py
      - name: Commit processed results
        env: { PAT: ${{ secrets.PAT }} }
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update with 4D box results" || echo "No changes"
          git pull --rebase origin main || true
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} HEAD:main
