name: Scrape 4D

on:
  schedule:
    - cron: '0 11 * * 3,6,0'
    - cron: '10 11 * * 3,6,0'
    - cron: '0 12 * * 3,6,0'
    - cron: '1 12 * * 3,6,0'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install --no-cache-dir openpyxl pandas requests
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs
          node -v
          npm -v
          npm install

      - name: Run task
        run: |
          TIME=$(date -u +"%H:%M")
          echo "Current UTC time is $TIME"
          if [[ "$TIME" == "12:01" ]]; then
            python3 4djson_Append_to_Excel.py
            python3 4dbox_script.py
          else
            npm run scrape
          fi

      - name: Commit & Push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update" || echo "No changes"
          git pull --rebase origin main || true
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} HEAD:main
