name: Scrape 4D

on:
  schedule:
    - cron: '40 10 * * 3,6,0'   # 6:40 PM SGT (npm run scrape)
    - cron: '50 10 * * 3,6,0'   # 6:50 PM SGT (npm run scrape)
    - cron: '0 11 * * 3,6,0'    # 7:00 PM SGT (npm run scrape)
    - cron: '10 11 * * 3,6,0'   # 7:10 PM SGT (npm run scrape)
    - cron: '0 12 * * 3,6,0'    # 8:00 PM SGT (npm run scrape)
    - cron: '1 12 * * 3,6,0'    # 8:01 PM SGT (Python scripts)
  workflow_dispatch:
    inputs:
      task:
        description: "Which task to run?"
        required: true
        default: "scrape"
        type: choice
        options:
          - scrape
          - python

jobs:
  scrape4d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install openpyxl pandas requests
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs
          npm install

      - name: Run task
        run: |
          echo "Triggered by schedule: '${{ github.event.schedule }}'"
          echo "Manual input task: '${{ github.event.inputs.task }}'"

          if [[ "${{ github.event.schedule }}" == "1 12 * * 3,6,0" || "${{ github.event.inputs.task }}" == "python" ]]; then
            echo "Running Python scripts..."
            python3 4dbox_script.py
            python3 4d_results_predictor.py
          else
            echo "Running npm scrape..."
            # npm run scrape
            python3 4d_results_predictor.py
          fi

      - name: Commit & Push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main || true
          git add -f 4d_results.csv 4d_box_output.xlsx 4d.json || true
          git commit -m "Auto update" || echo "No changes"
          git push https://x-access-token:$PAT@github.com/${{ github.repository }} HEAD:main
