name: Scrape 4D

on:
  # Existing schedules for 7:00 PM and 8:00 PM SGT
  schedule:
    - cron: '0 11 * * 3,6,0'  # 7:00 PM SGT
    - cron: '0 12 * * 3,6,0'  # 8:00 PM SGT
    - cron: '1 12 * * 3,6,0'  # 8:01 PM SGT (for Python script)

  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    if: github.event.schedule != '1 12 * * 3,6,0'  # Only run this job for Node.js scraping times

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm run scrape

      - name: Commit and push updated JSON
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add 4d.json
          git commit -m "Update 4D results" || echo "No changes to commit"
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} HEAD:main

  run-python-script:
    runs-on: ubuntu-latest
    if: github.event.schedule == '1 12 * * 3,6,0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas openpyxl requests

      - name: Run Python script
        run: python 4djson_Append_to_Excel.py  # replace with your actual filename
